export const patientColumns = [
  {
    key: "name",
    label: "Name",
    type: "text",
    required: true,
  },
  {
    key: "age",
    label: "Age",
    type: "number",
    required: true,
  },
  {
    key: "address",
    label: "Address",
    type: "text",
    required: true,
  },
  {
    key: "gender",
    label: "Gender",
    type: "text",
    required: true,
  },
  {
    key: "phone",
    label: "Phone Number",
    type: "tel",
    required: true,
  },
  {
    key: "bloodGroup",
    label: "Blood Group",
    type: "text",
    required: true,
  },
  {
    key: "email",
    label: "Email",
    type: "email",
    required: true,
  },
];

export const patients = [
  {
    id: 1,
    name: "Rahul Patel",
    age: 25,
    address: "Anand, Gujarat",
    gender: "Male",
    phone: "9876543210",
    bloodGroup: "B+",
    email: "rahul.patel@gmail.com",
  },
  {
    id: 2,
    name: "Priya Shah",
    age: 28,
    address: "Vadodara, Gujarat",
    gender: "Female",
    phone: "9876543211",
    bloodGroup: "O+",
    email: "priya.shah@gmail.com",
  },
  {
    id: 3,
    name: "Amit Desai",
    age: 34,
    address: "Ahmedabad, Gujarat",
    gender: "Male",
    phone: "9876543212",
    bloodGroup: "A+",
    email: "amit.desai@gmail.com",
  },
  {
    id: 4,
    name: "Neha Mehta",
    age: 31,
    address: "Surat, Gujarat",
    gender: "Female",
    phone: "9876543213",
    bloodGroup: "AB+",
    email: "neha.mehta@gmail.com",
  },
  {
    id: 5,
    name: "Karan Joshi",
    age: 42,
    address: "Rajkot, Gujarat",
    gender: "Male",
    phone: "9876543214",
    bloodGroup: "O-",
    email: "karan.joshi@gmail.com",
  },
  {
    id: 6,
    name: "Riya Patel",
    age: 23,
    address: "Nadiad, Gujarat",
    gender: "Female",
    phone: "9876543215",
    bloodGroup: "B+",
    email: "riya.patel@gmail.com",
  },
  {
    id: 7,
    name: "Vivek Shah",
    age: 37,
    address: "Gandhinagar, Gujarat",
    gender: "Male",
    phone: "9876543216",
    bloodGroup: "A-",
    email: "vivek.shah@gmail.com",
  },
  {
    id: 8,
    name: "Pooja Trivedi",
    age: 29,
    address: "Bharuch, Gujarat",
    gender: "Female",
    phone: "9876543217",
    bloodGroup: "O+",
    email: "pooja.trivedi@gmail.com",
  },
  {
    id: 9,
    name: "Harsh Patel",
    age: 46,
    address: "Mehsana, Gujarat",
    gender: "Male",
    phone: "9876543218",
    bloodGroup: "AB-",
    email: "harsh.patel@gmail.com",
  },
  {
    id: 10,
    name: "Sneha Shah",
    age: 26,
    address: "Vapi, Gujarat",
    gender: "Female",
    phone: "9876543219",
    bloodGroup: "A+",
    email: "sneha.shah@gmail.com",
  },
  {
    id: 11,
    name: "Dev Malhotra",
    age: 39,
    address: "Ahmedabad, Gujarat",
    gender: "Male",
    phone: "9876543220",
    bloodGroup: "B-",
    email: "dev.malhotra@gmail.com",
  },
  {
    id: 12,
    name: "Anjali Desai",
    age: 33,
    address: "Vadodara, Gujarat",
    gender: "Female",
    phone: "9876543221",
    bloodGroup: "O+",
    email: "anjali.desai@gmail.com",
  },
  {
    id: 13,
    name: "Manish Shah",
    age: 51,
    address: "Surat, Gujarat",
    gender: "Male",
    phone: "9876543222",
    bloodGroup: "A+",
    email: "manish.shah@gmail.com",
  },
  {
    id: 14,
    name: "Kavita Patel",
    age: 44,
    address: "Anand, Gujarat",
    gender: "Female",
    phone: "9876543223",
    bloodGroup: "B+",
    email: "kavita.patel@gmail.com",
  },
  {
    id: 15,
    name: "Nikhil Joshi",
    age: 30,
    address: "Rajkot, Gujarat",
    gender: "Male",
    phone: "9876543224",
    bloodGroup: "O-",
    email: "nikhil.joshi@gmail.com",
  },
  
  {
    id: 1,
    name: "Rahul Patel",
    age: 25,
    address: "Anand, Gujarat",
    gender: "Male",
    phone: "9876543210",
    bloodGroup: "B+",
    email: "rahul.patel@gmail.com",
  },
  {
    id: 2,
    name: "Priya Shah",
    age: 28,
    address: "Vadodara, Gujarat",
    gender: "Female",
    phone: "9876543211",
    bloodGroup: "O+",
    email: "priya.shah@gmail.com",
  },
  {
    id: 3,
    name: "Amit Desai",
    age: 34,
    address: "Ahmedabad, Gujarat",
    gender: "Male",
    phone: "9876543212",
    bloodGroup: "A+",
    email: "amit.desai@gmail.com",
  },
  {
    id: 4,
    name: "Neha Mehta",
    age: 31,
    address: "Surat, Gujarat",
    gender: "Female",
    phone: "9876543213",
    bloodGroup: "AB+",
    email: "neha.mehta@gmail.com",
  },
  {
    id: 5,
    name: "Karan Joshi",
    age: 42,
    address: "Rajkot, Gujarat",
    gender: "Male",
    phone: "9876543214",
    bloodGroup: "O-",
    email: "karan.joshi@gmail.com",
  },
  {
    id: 6,
    name: "Riya Patel",
    age: 23,
    address: "Nadiad, Gujarat",
    gender: "Female",
    phone: "9876543215",
    bloodGroup: "B+",
    email: "riya.patel@gmail.com",
  },
  {
    id: 7,
    name: "Vivek Shah",
    age: 37,
    address: "Gandhinagar, Gujarat",
    gender: "Male",
    phone: "9876543216",
    bloodGroup: "A-",
    email: "vivek.shah@gmail.com",
  },
  {
    id: 8,
    name: "Pooja Trivedi",
    age: 29,
    address: "Bharuch, Gujarat",
    gender: "Female",
    phone: "9876543217",
    bloodGroup: "O+",
    email: "pooja.trivedi@gmail.com",
  },
  {
    id: 9,
    name: "Harsh Patel",
    age: 46,
    address: "Mehsana, Gujarat",
    gender: "Male",
    phone: "9876543218",
    bloodGroup: "AB-",
    email: "harsh.patel@gmail.com",
  },
  {
    id: 10,
    name: "Sneha Shah",
    age: 26,
    address: "Vapi, Gujarat",
    gender: "Female",
    phone: "9876543219",
    bloodGroup: "A+",
    email: "sneha.shah@gmail.com",
  },
  {
    id: 11,
    name: "Dev Malhotra",
    age: 39,
    address: "Ahmedabad, Gujarat",
    gender: "Male",
    phone: "9876543220",
    bloodGroup: "B-",
    email: "dev.malhotra@gmail.com",
  },
  {
    id: 12,
    name: "Anjali Desai",
    age: 33,
    address: "Vadodara, Gujarat",
    gender: "Female",
    phone: "9876543221",
    bloodGroup: "O+",
    email: "anjali.desai@gmail.com",
  },
  {
    id: 13,
    name: "Manish Shah",
    age: 51,
    address: "Surat, Gujarat",
    gender: "Male",
    phone: "9876543222",
    bloodGroup: "A+",
    email: "manish.shah@gmail.com",
  },
  {
    id: 14,
    name: "Kavita Patel",
    age: 44,
    address: "Anand, Gujarat",
    gender: "Female",
    phone: "9876543223",
    bloodGroup: "B+",
    email: "kavita.patel@gmail.com",
  },
  {
    id: 15,
    name: "Nikhil Joshi",
    age: 30,
    address: "Rajkot, Gujarat",
    gender: "Male",
    phone: "9876543224",
    bloodGroup: "O-",
    email: "nikhil.joshi@gmail.com",
  },

];