export const patientColumns = [
  {
    key: "name",
    label: "Name",
    type: "text",
    required: true,
  },
  {
    key: "age",
    label: "Age",
    type: "number",
    required: true,
  },
  {
    key: "address",
    label: "Address",
    type: "text",
    required: true,
  },
  {
    key: "gender",
    label: "Gender",
    type: "text",
    required: true,
  },
  {
    key: "phone",
    label: "Phone Number",
    type: "tel",
    required: true,
  },
  {
    key: "bloodGroup",
    label: "Blood Group",
    type: "text",
    required: true,
  },
  {
    key: "email",
    label: "Email",
    type: "email",
    required: true,
  },
];

export const patients = [
  {
    id: 1,
    name: "Rahul Patel",
    age: 25,
    address: "Anand, Gujarat",
    gender: "Male",
    phone: "9876543210",
    bloodGroup: "B+",
    email: "rahul.patel@gmail.com",
  },
  {
    id: 2,
    name: "Priya Shah",
    age: 28,
    address: "Vadodara, Gujarat",
    gender: "Female",
    phone: "9876543211",
    bloodGroup: "O+",
    email: "priya.shah@gmail.com",
  },
  {
    id: 3,
    name: "Amit Desai",
    age: 34,
    address: "Ahmedabad, Gujarat",
    gender: "Male",
    phone: "9876543212",
    bloodGroup: "A+",
    email: "amit.desai@gmail.com",
  },
  {
    id: 4,
    name: "Neha Mehta",
    age: 31,
    address: "Surat, Gujarat",
    gender: "Female",
    phone: "9876543213",
    bloodGroup: "AB+",
    email: "neha.mehta@gmail.com",
  },
  {
    id: 5,
    name: "Karan Joshi",
    age: 42,
    address: "Rajkot, Gujarat",
    gender: "Male",
    phone: "9876543214",
    bloodGroup: "O-",
    email: "karan.joshi@gmail.com",
  },
  {
    id: 6,
    name: "Riya Patel",
    age: 23,
    address: "Nadiad, Gujarat",
    gender: "Female",
    phone: "9876543215",
    bloodGroup: "B+",
    email: "riya.patel@gmail.com",
  },

];